export const nodeIconIds: readonly string[] = [
  'book', 'database', 'server', 'cloud', 'users', 'user', 'shield', 'key', 'globe',
  'mail', 'bell', 'star', 'flag', 'zap', 'settings', 'cpu', 'terminal', 'file-text',
  'folder', 'image', 'link', 'git-branch', 'bug', 'alert-triangle', 'check-circle',
  'clock', 'dollar-sign',
];

export const nodeIconLabels: Record<string, string> = {
  book: 'Book / Docs',
  database: 'Database',
  server: 'Server',
  cloud: 'Cloud',
  users: 'Users / Team',
  user: 'User / Person',
  shield: 'Shield / Security',
  key: 'Key / Auth',
  globe: 'Globe / Web',
  mail: 'Mail',
  bell: 'Notification',
  star: 'Star / Favorite',
  flag: 'Flag / Milestone',
  zap: 'Zap / Fast',
  settings: 'Settings',
  cpu: 'CPU / Compute',
  terminal: 'Terminal / CLI',
  'file-text': 'File / Text',
  folder: 'Folder',
  image: 'Image',
  link: 'Link / URL',
  'git-branch': 'Git Branch',
  bug: 'Bug',
  'alert-triangle': 'Warning',
  'check-circle': 'Check / Done',
  clock: 'Clock / Time',
  'dollar-sign': 'Cost / Money',
};
